### ISSUE TITLE
Graph is empty

### ISSUE THREAD

**Issue by cmarquezrusso** [rilleralle/k8s-graph#9]
Hi Ralf,

I tried deploying k8s-graph into my k8s cluster but it didn't work.

The error is:

```
TypeError: Cannot read property 'map' of undefined
    at Server.extractNodes (/src/server.js:136:46)
    at Server.extractInformation (/src/server.js:65:38)
    at podsFetcher.fetch.then.then.result (/src/server.js:214:40)
    at &lt;anonymous&gt;
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Do you know where should I start looking at?

**Comment by rilleralle** [comment]
Hi @cristian04,

most probably this is a RBAC problem.
Have you tried to create a service account or give the default user admin rights as described in the README section RBAC?
https://github.com/rilleralle/k8s-graph#rbac

Let me quickly explain why this problem occures.
The deployment creates a pod with two containers. The pod will be executed with the default service account. 
1. The first container starts `kubectl proxy` mode so that I can access the required information to create the graph from the k8s API.
2. The second container starts this app, that is already available on Docker Hub rilleralle/k8s-graph. This app tires to get informations about the nodes, available namespaces and pods from http://127.0.0.1:8001/api/v1/nodes/, http://127.0.0.1:8001/api/v1/namespaces/ and for each available namespace http://127.0.0.1:8001/api/v1/namespaces/{namespace}/pods. You can check the code here https://github.com/rilleralle/k8s-graph/blob/master/src/server.js.The app can access the k8s API via localhost because they are both in the same pod.

The k8s API endpoints are secured with RBAC so the default service account does not have the previledge to access those endpoints by default.

Hope this helps.

Cheers,
Ralf

**Comment by cmarquezrusso** [comment]
I am trying `kubectl create clusterrolebinding kube-system-default-admin   --clusterrole=cluster-admin --serviceaccount=default:default` but it doesnt work.

**Comment by rilleralle** [comment]
Have you tried to delete the deployment, run the command and apply the deployment again?
If the problem still exits, please check the console in the browser again. The log message looks like this:
`Request to k8s failed.\nError message: ${e.message}`

**Comment by rilleralle** [comment]
I realized, that the logging was not sufficient enough so I pushed a new version. It is also already available on docker hub.
You will now see the raw API call responses in the browser console if an exception occurs.
The new feature was implemented in PR https://github.com/rilleralle/k8s-graph/pull/10

**Comment by cmarquezrusso** [comment]
Thanks for that PR :) really appreciated.

Im still receiving the same error: 

```
2018-05-14T01:26:28.926087319Z TypeError: Cannot read property 'map' of undefined
2018-05-14T01:26:28.926119241Z     at Server.extractNodes (/src/server.js:141:46)
2018-05-14T01:26:28.926123007Z     at Server.extractInformation (/src/server.js:70:38)
2018-05-14T01:26:28.926125541Z     at podsFetcher.fetch.then.then.result (/src/server.js:220:40)
2018-05-14T01:26:28.926138183Z     at &lt;anonymous&gt;
2018-05-14T01:26:28.926141372Z     at process._tickCallback (internal/process/next_tick.js:188:7)
```

I checked the deployed docker image and it's using the latest...

![image](https://user-images.githubusercontent.com/521587/39974140-bf38a114-577a-11e8-9994-fcaccf152813.png)

This is what I did...

```
$ kubectl delete -f k8s-graph.yaml
service "k8s-graph" deleted
deployment "k8s-graph" deleted
```
```
$ kubectl create clusterrolebinding kube-system-default-admin   --clusterrole=cluster-admin --serviceaccount=default:default

Error from server (AlreadyExists): clusterrolebindings.rbac.authorization.k8s.io "kube-system-default-admin" already exists
```
^ that was expected

```
$ git pull origin master
[...]
$ kubectl apply -f k8s-graph.yaml
service "k8s-graph" created
deployment "k8s-graph" created
```

Im still diagnosing this... will add more info here.

**Comment by rilleralle** [comment]
You welcome.

Can you please check the console in the browser? You should now see the API call results.

You can also try to ssh in the running graph pod and do an curl to `http://127.0.0.1:8001/api/v1/nodes/`
